checkout/frames-ios

Source/CardView.swift, Source/CvvInputView.swift, Tests/CvvInputViewTests.swift, Tests/Views/CardViewTests.swift
- Updated unit tests
This bug fix forces the English numberpad for the cvv input `textField`.  The bug it fixes allowed users with non-English numberpads to enter different characters, e.g. Arabic.
* [x ] Bugfix (non-breaking change which fixes an issue)
* [x ] Lint and unit tests pass locally with my changes
* [x ] I have added tests that prove my fix is effective or that my feature works
* [x ] I have added necessary documentation (if appropriate)
=> Changed CVV textfield keyboard type to asciiCapableNumberPad

Source/PhoneNumberInputView.swift
* [x ] Lint and unit tests pass locally with my changes
Fixed crash causing due to force wrapping a nil value when use back space for phone number text field.
=> MPI-243 : Fix for Edit phone number back space causing crash

FramesIos.xcodeproj/project.pbxproj, Source/PhoneNumberKit/Resources/update.sh
This PR removes `update.sh` from the project which is causing App Store rejections. This was added when updating PhoneNumberKit.
=> Remove PhoneNumberKit update.sh file

FramesIos.xcodeproj/project.pbxproj, Source/NetworkError.swift, Tests/NetworkErrorTests.swift
Fix logic in `NetworkError` where it would always return `.unknown` in the `init` method.
Add unit tests for `NetworkError`.
=> PIMOB-347: Add NetworkError tests

Documentation/Customizing the Card View.md, README.md, Source/CheckoutTheme.swift, Source/DetailsInputView.swift, Tests/DetailsInputViewTests.swift
This relates to issue https://github.com/checkout/frames-ios/issues/39.
Currently, there is no way of customizing the chevron colour, so it's difficult to get a dark mode looking right. This PR adds a property to `CheckoutTheme` that allows the modification of the color that will be applied to the chevron image. This defaults to `.black`, to maintain backwards compatibility.
Existing linting errors exist, but this change does not introduce any new ones. Unit tests pass.
=> Enable customization of chevron color

Package.swift, Source/CheckoutAPIClient+Constants.swift, Source/CheckoutAPIClient.swift, Source/Extensions/StringExtensions.swift, Source/UI/Views/SchemeIconsStackView.swift, Tests/Core/CheckoutAPIClientTests.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Resources now loading correctly through SPM
- Example SPM project now uses local version of Frames rather than version on Github
- Use version number from constants rather than from `Bundle`
- This is because the version number is not available on the bundle with SPM
None
=> fix: SPM resources and example project setup

Source/UI/CardListCell.swift, Source/UI/Views/DetailsInputView.swift
- Arrows and checkmarks were not loading for SPM due to reliance on resource structure (which SPM removes)
- Access arrows and checkmarks by file name only
=> fix: arrows and checkmarks not loading for SPM due to resource structure

Frames.podspec, Tests/Core/CheckoutAPIClientTests.swift, iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj, iOS Example Frame/Podfile.lock
Add app host for unit tests. This fixes an issue in Xcode 13 where we are unable to use the keychain without an app host.
=> PIMOB-738: fix keychain loader issue during tests

Source/UI/Controllers/ThreedsWebViewController.swift, Tests/UI/ThreedsWebViewControllerTests.swift, iOS Example Custom/Podfile.lock, iOS Example Frame/Podfile.lock
Use different delegate on `ThreedsWebViewController` to remove duplicate callbacks on delegate.
Very minor change. Should only require testing of 3DS flow
=> PI-1413: fix issue where 3ds callbacks were being called twice

Source/UI/Controllers/ThreedsWebViewController.swift, Tests/UI/ThreedsWebViewControllerTests.swift
Use non-persistent datastore for 3ds flow. This should discard any stored info after the end of the flow.
=> PI-1041: setup non-persistent datastore in 3ds flow

Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine1/DefaultBillingFormAddressLine1CellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/City/DefaultBillingFormCityCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/FullName/DefaultBillingFormFullNameCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/PhoneNumber/DefaultBillingFormPhoneNumberCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/Postcode/DefaultBillingFormPostCodeCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/State/DefaultBillingFormStateCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Main/DefaultBillingFormHeaderCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/Elements/Country/Country.swift, Source/UI/NewUI/BillingForm/Default Implementation/Elements/Error/DefaultErrorInputLabelStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift, Source/UI/NewUI/BillingForm/View/BillingFormHeaderCell.swift, Source/UI/NewUI/BillingForm/View/BillingFormPhoneNumberText.swift, Source/UI/NewUI/BillingForm/View/BillingFormTextField.swift, Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift, Source/UI/NewUI/CommonUI/View/ErrorView.swift, Source/UI/NewUI/CommonUI/View/SelectionButtonView.swift, Source/UI/NewUI/CommonUI/View/TableViewCell/CellButton.swift, Source/UI/NewUI/CommonUI/View/TableViewCell/CellTextField.swift, Source/UI/NewUI/CommonUI/View/TextFieldView.swift, Tests/UI/New UI/BillingForm/View/BillingFormButtonViewTests.swift
[Jira Ticket ](https://checkout.atlassian.net/browse/PIMOB-1240)
Change the background colour of the whole page
Be able to change the background colour of the whole billing form page in one go,  ( Currently  BillingFormStyle’s mainBackground only changes a part of the background as the table view, cells, components background overlaps and does not allow to change the background, By default the table view, cells, components background opacity should be 0. If a merchant wishes to change this should be able to change it via individual components which overrides the mainBackground color of BillingFormStyle.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. …
=> Fix: Change the background colour of the whole page

Source/UI/Controllers/CardViewController.swift, Source/UI/NewUI/BillingForm/Factory/BillingFormFactory.swift
=> Frames SDK API specs comments

Source/UI/NewUI/BillingForm/View/BillingFormHeaderCell.swift, Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift
[Jira ticket ](https://checkout.atlassian.net/browse/PIMOB-1240)
In landscape mode ( iPhones only ) the form header is having different width than the form elements .
=> Fix header view landscape

Source/Resources/en.lproj/Localizable.strings, Source/UI/Controllers/AddressViewController.swift, Source/UI/Controllers/CountrySelectionViewController.swift, Source/UI/Delegates/CountrySelectionViewControllerDelegate.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine1/DefaultBillingFormAddressLine1CellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine2/DefaultBillingFormAddressLine2CellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/City/DefaultBillingFormCityCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/Country/DefaultBillingFormCountryCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/FullName/DefaultBillingFormFullNameCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/PhoneNumber/DefaultBillingFormPhoneNumberCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/Postcode/DefaultBillingFormPostCodeCellStyle.swift, Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/State/DefaultBillingFormStateCellStyle.swift, Source/UI/NewUI/BillingForm/View/BillingFormPhoneNumberText.swift, Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift, Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift, Source/UI/NewUI/CommonUI/Protocols/Cell/CellStyle.swift, Source/UI/NewUI/CommonUI/View/SelectionButtonView.swift, Source/UI/NewUI/CommonUI/View/TableViewCell/CellButton.swift, Source/UI/NewUI/CommonUI/View/TableViewCell/CellTextField.swift, Source/UI/NewUI/CommonUI/View/TextFieldView.swift, Tests/Mocks/BillingFormTextFieldCellMockDelegate.swift, Tests/Mocks/BillingFormViewControllerMockDelegate.swift, Tests/UI/AddressViewControllerTests.swift, Tests/UI/CountrySelectionViewControllerTests.swift, Tests/UI/New UI/BillingForm/View/BillingFormButtonViewTests.swift, Tests/UI/New UI/BillingForm/View/BillingFormTextFieldViewTests.swift, Tests/UI/New UI/BillingForm/ViewModel/BillingFormViewModelTests.swift
[Jira ticket ](https://checkout.atlassian.net/browse/PIMOB-1240)
Add country into the correct field when the fields passed in BillingFormCell are changes
Issue: 
When I add a country in, it should always go in the country field even if I change how many fields are passed in BillingFormCell
BillingFormFactory.defaultBillingFormStyle contains 8 BillingFormCell injected, if this is changed to 7 the editing of each text field value is seen to be impacted and interchanged which is not expected. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we …
=> PIMOB-1240: Fix billing form cells order

Source/Resources/en.lproj/Localizable.strings, Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift, Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1274?atlOrigin=eyJpIjoiMDM3ODgxNTJlYTU3NDJlNWJlMGViNzlkNTRmYjY3NjMiLCJwIjoiaiJ9)
An invalidMonth would be anything not between [01 - 12]
So if a user inputs 21 as the month, that is of course an invalid month. 
We will handle this with smart month logic, whereby 
if user enters a 0, let them enter any digit between 1-9
if user enters a 1, let them enter any digit between 0-2
if user enters a number between 2-9, then move to the year selector and append a 0 before the digit 
Smart year logic:
User must enter a number between 2-9 to start with 
Happens with a negative year or unexpected value. This would never occur with the keypad
_Put …
=> Feature/PIMOB-1274: Expiry date validation logic

Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift, Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
[Jira ticket](https://checkout.atlassian.net/jira/software/c/projects/PIMOB/boards/988?modal=detail&selectedIssue=PIMOB-1191)
I am a customer of the Merchant | I use the expiry date component | I’m unable to add an MM/YY in that is before the current MM/YYFor example, if the month is 06/22, I cannot add a date of 05/22 in
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did …
=> fix: if the month is 06/22, I cannot add a date of 05/22

Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Bug: 
- when user leave billing form optional field with empty value, it will add gap in summary view
=> PIMOB-1304:Fix summary value empty value

Source/Core/Constants/Constants+LocalizationKeys.swift, Source/Core/Constants/Constants+Style.swift, Source/Resources/en.lproj/Localizable.strings, Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentHeaderCellStyle.swift, Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Standard validation error text for County is incorrect
Should be:Missing county
Payment header and subtitle 
Fix:
=> PIMBO-1337: Update some localisations

Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift, Source/UI/NewUI/BillingForm/ViewModel/BillingFormViewModel.swift, Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift, Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/Mocks/BillingFormViewModelMockDelegate.swift, Tests/UI/New UI/BillingForm/ViewController/BillingFormViewControllerTests.swift, Tests/UI/New UI/BillingForm/ViewModel/BillingFormViewModelTests.swift, Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
[Jira task](https://checkout.atlassian.net/browse/PIMOB-1279)
✅ Added event when billing vc is getting shown to the user. As owner of the whole journey and already responder of billing updates, I've user Payment view model to receive callback when billing is shown and then trigger event.
🤔 Would be tempted to create a wrapper around Payment VM to remove the responsibilities not strictly within its purpose, but I'm on the edge currently if that's needed. The new object overhead may not justify the benefit for now. Definitely may be a tech debt task creeping up
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
=> PIMOB-1279: Trigger analytics event on billing VC willAppear

Checkout/Checkout/Integration/CardValidatorTests.swift
Enable pipelines to not show false failures when some place on Earth is still one month behind compared to the location running the test
=> [BUG] - fix unit tests blocking pipelines

Source/UI/NewUI/CommonUI/View/Component/InputView.swift
- Component border colour should turn red when there is an error on the payment page 
- When there is an error I should see the border of the component red, as you can see here it stays black This issue does not occur on the billing page 
=> PIMOB-1337: Fix error border line for payment UI components 

Checkout/Checkout/Source/Model/Card+Scheme.swift, Checkout/Checkout/Test/Model/CardSchemeTests.swift, Checkout/Checkout/Test/Validation/CVVValidatorTests.swift
[Jira task](https://checkout.atlassian.net/browse/PIMOB-1366)
Enable a CVV length of 0 for Maestro cards
=> PIMOB-1366: Enable maestro to validate without cvv

Source/UI/NewUI/PaymentForm/View/CardNumber/CardNumberViewModel.swift, Tests/UI/New UI/PaymentForm/CardNumber/CardNumberViewModelTests.swift
[Jira task](https://checkout.atlassian.net/browse/PIMOB-1366)
In [Previous PR](https://github.com/checkout/frames-ios/pull/242) maestro cards were compared using their associated value (the card number length). Given all `supportedSchemes` come from a parsing that assigns a 0 length as supported, any length maestro would get refused as not supported.
Have improved the check whether we support the detected scheme to ignore any associated value and match regardless of that value.
=> PIMOB-1366: Fix accepting maestro cards

iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj
The logic should be something along the lines of:
- If Homebrew is installed as x86 using Rosetta, then we should use the Rosetta path (/usr/bin/env )
- If Homebrew is installed as arm64, then we should use the M1 path (opt/homebrew)
If this is a …
=> PIMOB-XXXX: Fix swift lint for M1

Checkout/Checkout/Source/Model/Card+Scheme.swift, Checkout/Checkout/Test/Validation/CardNumberValidatorTests.swift
[Jira task](https://checkout.atlassian.net/browse/PIMOB-1415)
Changing Discover regex to better match eagerly and completely the checked card numbers.
[Source of Regex](https://stackoverflow.com/a/23231321) (_SO_)
[BIN numbers documentation](https://www.bincodes.com/bin-list/) (not 100% source of truth but reasonable guidance)
[Regex validator](https://www.regexpal.com) (have also ran locally to confirm the number provided in the task is behaving correctly.
Have also changed the order of identification for regexes, setting VISA regex to check and setting Discover ahead of Maestro. Reason for this is the overlap on BIN ranges (see BIN numbers link, VISA has all the 4... range)
=> PIMOB-1415: Update Discover card scheme regex

Source/Core/Logging/FramesLogEvent.swift, Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/Core/Logging/FramesLogEventTests.swift, Tests/Mocks/StubCheckoutAPIService.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Create new logging event and trigger on button press.
Found an inconsistency in some unit test where a helper method was named inaccurately.
=> PIMOB-1362(2): Create & Use paymentFormSubmitted logging event

Source/Core/Logging/FramesLogEvent.swift, Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/Core/Logging/FramesLogEventTests.swift, Tests/Mocks/StubCheckoutAPIService.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift, Tests/UI/PaymentForm/PaymentViewControllerTests.swift
Create new logging event and trigger on completion of tokenisation request.
Report failure of request via a new `warn`  event.
=> PIMOB-1362(3): Create & Use paymentFormOutcome logging event 

Source/Core/Logging/FramesLogEvent.swift, Source/UI/PaymentForm/ViewController/PaymentViewController.swift, Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Source/UI/PaymentForm/ViewModel/PaymentViewModel.swift, Tests/Core/Logging/FramesLogEventTests.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Create new logging event and trigger when the back arrow is pressed to dismiss the payment view controller. This is user initiated and would equate to a cancel action from the user.
=> PIMOB-1362(4): Create & Use paymentFormCanceled logging event

Source/Core/Logging/FramesLogEvent.swift, Source/UI/BillingForm/ViewModel/BillingFormViewModel.swift, Source/UI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift, Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/Core/Logging/FramesLogEventTests.swift, Tests/Mocks/BillingFormViewModelMockDelegate.swift, Tests/UI/BillingForm/ViewModel/BillingFormViewModelTests.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Create new logging events:
- `billingFormCanceled` - Triggered when user presses Cancel (will ignore any changes that may have taken place)
- `billingFormSubmit` - Triggered when user presses Done (only enabled once some changes were made on form)
=> PIMOB-1362(5): Create & Use Billing form lifecycle logging events

Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
As [raised in previous PR from chain](https://github.com/checkout/frames-ios/pull/315#discussion_r989928317), pressing the Done button if card details cannot be generated (for now this means missing any number input or expiry date) would result in a silent fail.
Changes proposed log this failure as its something we should not expect to happen, as the pay button getting enabled has more stringent conditions than the card object creation. If it does occur it would be of interest to fix & review processes into how it appeared.
=> PIMOB-1362(6): Create & Use paymentFormSubmitted logging event

Source/UI/PaymentForm/ViewController/PaymentViewController.swift
Replace usage of [keyboardFrameBeginUserInfoKey](https://developer.apple.com/documentation/uikit/uiresponder/1621616-keyboardframebeginuserinfokey) for the estimate of keyboard height with [keyboardFrameEndUserInfoKey](https://developer.apple.com/documentation/uikit/uiresponder/1621578-keyboardframeenduserinfokey).
This is an intended correction, as per their own documentations:
- `keyboardFrameEndUserInfoKey`: A user info key to retrieve the keyboard’s frame **at the end of its animation**
- `keyboardFrameBeginUserInfoKey`: A user info key to retrieve the keyboard’s frame **at the beginning of its animation**
As we need the size to calculate offset needed, the final size would be the most accurate value to use.
=> PIMOB-XXXX: Improve automatic scroll on keyboard appearance

README.md
Carthage wants a minor version number and is not happy simply with a major
```
github "checkout/frames-ios" ~> 4
```
Someone integrating via Carthage will end up with an error and follow up by adding a `.0` after the version, to:
```
github "checkout/frames-ios" ~> 4.0
```
PR will offer correct syntax in ReadMe to prevent issue and time spent understanding it.
=> PIMOB-XXXX: Correct ReadMe Carthage dependency installation

Checkout.podspec, Frames.podspec, iOS Example Frame/Podfile, iOS Example Frame/Podfile.lock
The pod specs were not linting correctly for releases. This is due to structure changes and mostly misplaced unit tests.
As we are using SPM for our core development & pipeline tests, the tests are already being ran and validated so it doesn't make sense to worry about distributing the pods with unit tests?
I took the easy way and removed them from the podspec.
=> PostRelease: Fix podspec 

Source/UI/3DS/ThreedsWebViewController.swift, Tests/UI/3DS/ThreedsWebViewControllerTests.swift, iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift
The VC was requesting a network client as part of the initialisation, but only consuming the logging part of the network client, discarding the rest.
Changed initialiser to only request an environment, and use that to create logger directly, reducing complexity and unnecessary overhead.
This will require update of ReadMe & Public Docs, but that may be done as part of the next release, not this PR (since latest release is in sync with the current docs & change would not be available via the actual release)
=> PIMOB-XXXX: Remove overhead from ThreeDSWebViewController initialiser

Source/Extensions/UINavigationControllerExtensions.swift, Tests/Core/Extensions/UINavigationControllerTests.swift, iOS Example Frame/iOS Example Frame/Extension/UIViewControllerExtension.swift
Fix: When Billing form screen is scrolled, the navigation bar background color is changed.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
=> PIMOB-1474: Fix navigation bar background color on scrolling

CHANGELOG.md, Checkout/Checkout/Source/Tokenisation/Error/TokenisationError+TokenRequest.swift, Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
By passing the cancellation as an error of `userCancelled`, the consumer can successfully track the occurrence of this event.
Will require product review and internal discussion over possible alternatives that may fit better into the product roadmap.
=> Release 4.0.4: Pass UserCancelled in completion handler

Checkout/Checkout/Source/Tokenisation/Error/TokenisationError+TokenRequest.swift, Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift
By passing the cancellation as an error of `userCancelled`, the consumer can successfully track the occurrence of this event.
Will require product review and internal discussion over possible alternatives that may fit better into the product roadmap.
=> PIMOB-XXXX: Pass user cancelled event in the completion handler

CHANGELOG.md, Checkout/Checkout/Source/Model/TokenDetails.swift, Checkout/Checkout/Source/Tokenisation/TokenDetailsFactory.swift, Checkout/Sample/Source/Card Tokenisation/CardTokenizationViewController.swift, CheckoutTests/Integration/CheckoutAPIServiceIntegrationTests.swift, CheckoutTests/Stubs/StubProvider.swift, CheckoutTests/Tokenisation/TokenDetailsFactoryTests.swift, Tests/Mocks/StubCheckoutAPIService.swift, iOS Example Apple Pay/iOS Example Apple Pay/ViewController.swift, iOS Example Frame/iOS Example Frame/Factory/Factory.swift, iOS Example/iOS Example/ExampleViewController.swift
As schemes may come and go, removing the enum parsing in the object will future proof SDK support. This enables consumers (going as far as end mobile application), to recognise tokens created by new card schemes without the need to getting the latest SDK version.
=> Release 4.0.4: Do not parse network response for scheme

Checkout/Checkout/Source/Tokenisation/CheckoutAPIService.swift, Checkout/Checkout/Source/Tokenisation/Error/TokenisationError+TokenRequest.swift, CheckoutTests/CheckoutErrorTests.swift, CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift, Package.swift, Source/Extensions/PhoneExtensions.swift, Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift, iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift
[PIMOB-1972](https://checkout.atlassian.net/browse/PIMOB-1972)
Create new error and return when tokenisation is attempted and an API Key does not exist.
❌ Change **does not** perform validation on the key! It simply validates that a value is provided
✔️ New error will get reported within the current analytics flows
*** 
🔴 This is an API breaking change, but is also auto corrected by using Xcode. The break only appears if consumer application is using a switch statement to iterate via errors returned by SDK. Xcode can however autoupdate the syntax to include the new `case`, making it a minor hurdle to overcome.
🟡 We may reduce impact of the breaking change if we move the error within `NetworkError`, where it will only break if the consumer application uses a switch statement on the …
=> PIMOB-1972: Add new error type for missing API Key

Source/Extensions/CAShapeLayerExtension.swift, Source/UI/BillingForm/View/BillingFormTextFieldView.swift, Source/UI/CommonUI/View/Component/BorderView.swift, Source/UI/CommonUI/View/Component/InputView.swift, Source/UI/CommonUI/View/Core/ButtonView.swift, Source/UI/PaymentForm/View/BillingFormSummaryView.swift, Source/UI/PaymentForm/ViewController/PaymentViewController.swift, Tests/UI/CommonUI/BorderViewTest.swift
[Jira task](https://checkout.atlassian.net/browse/PIMOB-2012)
Due to the background colour currently being assigned directly to UIView, it does not account for the custom border behaviour we enable.
The current border layer does not have to be complete as we support custom behaviour, so the solution proposed is to create another layer with a complete path that copies the border. We then use this as a background layer and assign the colour to it.
***
**Possible outcome of this change:**
=> PIMOB-2012: Add background layer to borders

.swiftlint.yml, Source/Extensions/CAShapeLayerExtension.swift, Source/UI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift, Source/UI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift, Source/UI/BillingForm/Default Implementation/Elements/Country/DefaultCountryFormButtonStyle.swift, Source/UI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift, Source/UI/BillingForm/View/BillingFormTextFieldView.swift, Source/UI/CommonUI/Protocols/Elements/ElementBorderStyle.swift, Source/UI/CommonUI/Protocols/Elements/ElementButtonStyle.swift, Source/UI/CommonUI/Protocols/Elements/ElementTextFieldStyle.swift, Source/UI/CommonUI/View/Component/BorderView.swift, Source/UI/CommonUI/View/Component/InputView.swift, Source/UI/CommonUI/View/Core/ButtonView.swift, Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultAddBillingDetailsButtonStyle.swift, Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultEditBillingDetailsButtonStyle.swift, Source/UI/PaymentForm/Default Implementation/BillingFormSummary/Summary/View/DefaultBillingSummaryViewStyle.swift, Source/UI/PaymentForm/Default Implementation/DefaultPayButtonFormStyle.swift, Source/UI/PaymentForm/StyleProtocol/BillingSummaryViewStyle.swift, Source/UI/PaymentForm/View/BillingFormSummaryView.swift, Source/UI/PaymentForm/ViewController/PaymentViewController.swift, Source/UI/Theme/Generic/Theme+Border.swift, Source/UI/Theme/Generic/Theme+Button.swift, Source/UI/Theme/Generic/Theme+TextField.swift, Source/UI/Theme/PaymentForm/Theme+AddBillingSectionButton.swift, Source/UI/Theme/PaymentForm/Theme+BillingSummary.swift, Source/UI/Theme/PaymentForm/Theme+PayButton.swift, Source/UI/Theme/Theme.swift, Tests/UI/CommonUI/BorderViewTest.swift, iOS Example Frame/iOS Example Frame/Factory/Factory+UITest.swift, iOS Example Frame/iOS Example Frame/ThemeDemo.swift
[Jira task](https://checkout.atlassian.net/browse/PIMOB-2011)
Middle layer between 4.0.x versions and future 4.1.0 to avoid existing users facing syntax breaking changes on update.
***
Side effects of the changes in current form:
Our SDK will trigger 13 warnings that originate from the SDK to the application consuming SDK. In the current approach of using interfaces for the styling objects we are unable to transition without triggering those warnings.
In our Default objects we are able to avoid by introducing an internal state that aligns the new destination and the deprecated location. Protocols cannot however contain state so do not allow this.
=> PIMOB-2011: Avoid breaking API for borders release

iOS Example Frame SPM/iOS Example Frame Regression Tests/CardValidationTests.swift, iOS Example Frame SPM/iOS Example Frame Regression Tests/Helpers/StaticTexts.swift, iOS Example Frame SPM/iOS Example Frame Regression Tests/Helpers/TestCard.swift
Tests if we verify the security code lengths depending on the requirements of the card schemes.
=> Add test cases for every card scheme's security code verifications

bitrise.yml
We had renamed integration tests to regression tests, therefore, we needed to update the name of the workflow on main branch since Bitrise gets the config from main.
=> Fix bitrise yml

Source/UI/PaymentForm/View/ExpiryDate/ExpiryDateFormatter.swift, Source/UI/PaymentForm/View/ExpiryDate/ExpiryDateView.swift, Source/UI/PaymentForm/ViewController/PaymentViewController.swift, Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift, Tests/Mocks/MockExpiryDateViewDelegate.swift, Tests/Mocks/PaymentViewControllerMockDelegate.swift, Tests/UI/BillingForm/View/ExpiryDateFormatterTests.swift, Tests/UI/BillingForm/View/ExpiryDateViewTests.swift
`CardValidator` was solid and was returning the error but `ExpiryDateFormatter` was not using that error information and also was overriding any kinds of errors that was being propagated through. 
This PR uses a central point of verification for expiry date validation and depends on CardValidator only.
=> PIMOB 2058 - expiry date validation

Checkout/Checkout/Source/Extension/Foundation+Extensions.swift, Checkout/Checkout/Source/Protocols/CalendarProtocol.swift, Checkout/Checkout/Source/Validation/Validators/CardValidator.swift, CheckoutTests/Stubs/StubCalendar.swift, CheckoutTests/Validation/CardValidatorTests.swift
Card validator tests were not actually testing anything. They needed a custom way to get a pre defined date. 
This will also help us to override the system time and test expiry date edge cases in the upcoming automated regression tests.
=> Card validator improvement

Checkout.podspec, Checkout/Checkout/Source/Validation/Constants.swift, CheckoutTests/Network/RequestFactoryTests.swift, Frames.podspec
Release 4.1.1 with the latest expiry date hotfixes
=> Bump version to 4.1.1

Checkout/Samples/Package.swift, iOS Example Frame SPM/Package.swift, iOS Example Frame/Package.swift
Merchants don't need to download our sample projects into their application bundle. Especially after the addition of many snapshots. This PR removes them. The only working way of achieving this is adding empty `Package.swift` files as the other ways don't work.
=> Exclude sample projects from package distribution

CHANGELOG.md, Checkout/Checkout.podspec, Checkout/Source/Validation/Constants.swift, CheckoutTests/Network/RequestFactoryTests.swift, Frames.podspec, Source/Core/Constants/Constants.swift
- Structural changes
- Carthage support and sample project removal
- Automated regression tests
- Removal of the sample projects from the SPM distribution (they were already excluded on CocoaPods distribution)
=> Bump version to 4.2.0

README.md
Remove Carthage references from README.
New README file preview can be found [here](https://github.com/checkout/frames-ios/blob/d133fc32a46db07c9c80b3fd34f43213c575b891/README.md)
=> Remove Carthage references from README

Checkout/Samples/CocoapodsSample/Podfile, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile
We needed a trigger point to know if our latest release versions work. Because, sometimes the pods don't get updated and we use the old version without knowing. We also have a safety mechanism by doing this we have to get the new version numbers through PR reviews.
=> Update sample project versions to exact versions

.github/workflows/check-pr.yml, .github/workflows/codeql-analysis.yml
Check PR status via GitHub Actions. [JIRA](https://checkout.atlassian.net/browse/PIMOB-2127?atlOrigin=eyJpIjoiYTY1MWQ2MWFkYTdmNDcxMWE5OTAyNTc2OWEyYTljMTEiLCJwIjoiaiJ9)
Bitrise workflow to be removed with a separate PR. It's needed in this PR to prove that we didn't break anything. 
We needed to run tests other than the UI tests on `macOS-13` and `Xcode-14.3` since the other versions had a bug and were failing our tests.
The steps that are transferred from Bitrise:
=> Add workflow to check PR status

bitrise.yml
We're in the process of transferring all the Bitrise workflows into GitHub Actions workflows. We already merged `pr-checks` workflow, so, this PR removes the counterpart thereof.
=> Remove PR checks from Bitrise in favour of GitHub Actions

bitrise.yml
They are moved to GitHub Actions
=> Remove regression tests from bitrise.yml

.github/workflows/check-pr.yml, .swiftlint.yml
- SwiftLint comes pre-installed on runner images of GitHub.
- SwiftLint will run before all the other checks. 
- If SwiftLint fails, then all the other checks don't run. This is made possible by the `needs:` mark.
- SwiftLint only runs for the new files to avoid a big PR
- It also parses errors and warnings for the new files and shows them on GitHub UI: (even though we won't get any warnings and will convert them to errors for new files. This is made possible by `--strict` flag. Parsing is made by using `sed -E`)
- If there are no changes in `.swift` files, then it skips linting and marks the job as a success.
- If there are changes in `.swift` files, then SwiftLint only lints them:
=> Add SwiftLint as a blocker pre-check for all the other checks

.github/scripts/buildDocs.sh, .github/workflows/generate-jazzy-docs.yml, .jazzy.yaml
Provide an easy way to generate jazzy docs by one click
=> Add generate-jazzy-docs.yml

iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
We needed to define an exact version since they stopped supporting iOS 12 in a minor version release. This broke our CI/CD pipeline.
=> Update SnapshotTesting framework version

.github/workflows/run-regression-tests.yml, .github/workflows/validate-for-app-store.yml
`Run Regression Tests` and `Validate App Store` was added as requirements for all the PRs that target the `main` branch. I hoped that we could manually run those two workflows and satisfy the PR requirements. But, PR status checks don't get updated even after those workflows succeed, if they are triggered manually. So, the only way to make it work is to trigger them via PR labels. 
I also left manual run capability in place, we can use it if need be.
=> Trigger regression and validation workflows via labels

.github/scripts/lintEditedFiles.sh, Source/Core/Constants/AccessibilityIdentifiers.swift, Source/UI/PaymentForm/View/PaymentHeaderView.swift, Source/UI/PaymentForm/View/SecurityCodeView.swift, Source/UI/SecurityCodeComponent/DefaultSecurityCodeFormStyle+Extension.swift, Source/UI/SecurityCodeComponent/SecurityCodeComponent.swift, Source/UI/SecurityCodeComponent/SecurityCodeComponentConfiguration.swift, Source/UI/SecurityCodeComponent/SecurityCodeComponentStyle.swift, Tests/UI/SecurityCodeComponent/SecurityCodeComponentTests.swift, iOS Example Frame SPM/iOS Example Frame Regression Tests/Helpers/TestCard.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/iOS Example Frame/Storyboards/Base.lproj/Main.storyboard, iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift, iOS Example Frame/iOS Example Frame/ViewController/SecurityCodeViewController.swift, iOS Example Frame/iOS Example FrameUITests/SecurityCodeComponentUITests.swift, iOS Example Frame/iOS Example FrameUITests/XCUIApplication+Extension.swift
JIRA-2167
Add Security Code Component UI.
> 1. Go to the main screen
> 2. Tap on CVV Component button
> 3. Verify the screen is visible and the validation works
* [N/A] I have added regression tests that prove my fix is effective or that my feature works
Just having a set of basic UITests felt enough. No need for detailed regression tests. If you see some scenarios that'd do well with extensive regression tests being written upon, please add a comment to this PR.
=> Implement security code component UI

Checkout/Source/Logging/CheckoutLogEvent+Types.swift, Checkout/Source/Logging/CheckoutLogEvent.swift, Checkout/Source/Network/Models/SecurityCode/SecurityCodeRequest.swift, Checkout/Source/Tokenisation/CheckoutAPIService.swift, CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
JIRA-2169
Log the token requested and response events for the newly introduced security code component
_If there's any functionality change, please list a step by step guide of how to verify the changes, and/or upload a screen recording for any visible changes._
> For instance:
> 1. Go to the main screen
> 2. Tap on `Security Code Component` button
> 3. Verify the relevant logs are being uploaded.
Token requested success log is [here](https://app.datadoghq.com/logs?query=%40ApplicationName%3Acloudevents%20%40platform%3AiOS%20%40appPackageNam …
=> Implement logging for the security code component

iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
Resolve merge conflicts of main to develop PR
=> Resolve merge conflicts of main to develop PR

.github/CHANGELOG.md, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile, iOS Example Frame/Podfile.lock
Update sample project versions and changelog.
=> Update sample project versions and changelog.

CheckoutTests/Integration/CheckoutAPIServiceIntegrationTests.swift, Source/UI/PaymentForm/Model/PaymentStyle.swift, Source/UI/PaymentForm/ViewController/FramesPaymentViewController.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile, iOS Example Frame/iOS Example Frame/Factory/Factory.swift
An SDK integrator is able to disable the billing address on the prebuilt UI. Currently they can only do this via the customisable UIs. When they disable the billing address, it doesn’t show on the prebuilt UI
_Issue ticket number and link._
[PIMOB-2358](https://checkout.atlassian.net/browse/PIMOB-2358)
Make billingFormStyle optional which will be checked against while creating default views.
_If there's any functionality change, please list a step by step guide of how to verify the changes, and/or upload a screen recording for any visible changes._
> For instance:
> 1. Go to the main screen
> 2. Tap on Default
> 3. Verify the billing address view is removed
[PIMOB-2358]: https://checkout.atlassian.net/browse/PIMOB-2358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> [Frames-iOS] - Allow billing address to be disabled on the prebuilt UI

.github/partial-readmes/MakeItYourOwn.md, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile
UpdatedREADME to deactivate the billing address in Default view.
README did not mention any way to deactivate billing address
_Issue ticket number and link._
[PIMOB-2355](https://checkout.atlassian.net/browse/PIMOB-2355)
README updated with how to disable the billing address
[PIMOB-2355]: https://checkout.atlassian.net/browse/PIMOB-2355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Frames-iOS] - Update ReadMe with how to disable billing address

.github/workflows/run-regression-tests.yml, .github/workflows/validate-for-app-store.yml
- Add the capability of manual triggering for `Run Regression Tests` and `Validate For App Store` workflows
- Fix a failing regression test case
=> Make some workflows to be able to run manually

.github/workflows/publish-Checkout.podspec.yml, .github/workflows/publish-Frames.podspec.yml
We want to make sure that Publish Checkout.podspec and Publish Frames.podspec can only be run from a protected release/* branch and otherwise must fail. Added a step to check the current branch and fail if it's not the expected branch. 
[PIMOB-2409](https://checkout.atlassian.net/browse/PIMOB-2409)
[PIMOB-2409]: https://checkout.atlassian.net/browse/PIMOB-2409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Let Publish Checkout.podspec and Publish Frames.podspec to be run from specific branches only

.github/workflows/codeql-analysis.yml
Initially, CodeQL was scanning 224/410 files because it was just taking Frames into account.
Added FramesTests also as part of CodeQL scan.
Now 304/410 files are being scanned.
[PIMOB-2428](https://checkout.atlassian.net/browse/PIMOB-2428)
[PIMOB-2428]: https://checkout.atlassian.net/browse/PIMOB-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Analyze CodeQL scanned files

.github/CHANGELOG.md, Checkout.podspec, Checkout/Samples/CocoapodsSample/Podfile, Checkout/Samples/SPMSample/CheckoutSPMSample.xcodeproj/project.pbxproj, Checkout/Samples/SPMSample/CheckoutSPMSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Checkout/Source/Validation/Constants.swift, Frames.podspec, Source/Core/Constants/Constants.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS Example Frame/Podfile
Bump versions to prepare a new release v4.3.2 for `Checkout` and `Frames`
Ticket on release board is [here](https://checkout.atlassian.net/browse/RELEASE-27506?atlOrigin=eyJpIjoiODY2ODA0ZWQ2ZjIwNDEzNjhiYjg4MjViN2QwYThkZTAiLCJwIjoiaiJ9).
=> Update/release preparation 4.3.2

.github/CHANGELOG.md, .github/workflows/publish-Checkout.podspec.yml, .github/workflows/publish-Frames.podspec.yml, Checkout.podspec, Checkout/Samples/CocoapodsSample/Podfile, Checkout/Samples/SPMSample/CheckoutSPMSample.xcodeproj/project.pbxproj, Checkout/Source/Validation/Constants.swift, Frames.podspec, Source/Core/Constants/Constants.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile
Bump versions to prepare a new release v4.3.3 for Checkout and Frames
=> Update version to 4.3.3

Checkout/Source/Tokenisation/CheckoutAPIService.swift, CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift
We didn't have have payment type being `card` or `applepay` in error logs. Now we're adding it.
=> Send payment type in error logs

.github/workflows/check-pr.yml, Checkout.podspec, Checkout/Source/Tokenisation/CheckoutAPIService.swift, Package.resolved, Package.swift
https://checkout.atlassian.net/browse/PRISM-11216
- Updates the Risk SDK version to 3.0.0 which adds correlationID as a metadata instead of a direct event arguement which also changes the structure of receiving the frames options collecting more data(product name, version and correlationID) to improve the log tracing.
- Moves Risk config and initialisation after the log manager initialisation since the `setup` method calls a `resetCorrelationID` method which updates the correlationID.
No internal changes made.
=> Update how Frames options are sent to Risk SDK

.github/workflows/validate-for-app-store.yml, Checkout.podspec, Checkout/Samples/CocoapodsSample/Podfile, Checkout/Samples/SPMSample/CheckoutSPMSample.xcodeproj/project.pbxproj, Checkout/Source/Validation/Constants.swift, Frames.podspec, Source/Core/Constants/Constants.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile
Uses the new version of Risk SDK. We were getting reports of a crash relevant to RIsk SDK logging improvement. The issue did not happen in 4.3.2 but only on 4.3.3 and 4.3.4. We couldn’t reproduce the crash and it’s intermittent for client developers as well. We wanted to do our best bet and alter the usage of logger SDK in Risk SDK. We’ll release version 4.3.5 and add some warning labels for v4.3.3 and v4.3.4. We won’t retire or roll them back, because unless someone intentionally uses those versions, they will be skipped by SPM’s automatic dependency resolver and all the client apps will be updated to 4.3.5 in their next iteration of app compilations.
Will address #526
=> Bump sample project versions to 4.3.5

Checkout.podspec, Checkout/Source/Logging/CheckoutLogEvent.swift, Checkout/Source/Tokenisation/CheckoutAPIService.swift, CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift, Package.resolved, Package.swift
https://checkout.atlassian.net/browse/PRISM-11245
Await acitons on the Risk SDK before continuing.
No changes in interaction or operation or test order.
NB: Regardless of success or failure within Risk, the completion handler is called on both scenarios.
NB: All asynchronous actions have a maximum timeout of 5 seconds.
=> Await risk sdk actions

Checkout/Samples/CocoapodsSample/Podfile, Checkout/Source/Logging/CheckoutLogEvent.swift, Checkout/Source/Tokenisation/CheckoutAPIService.swift, CheckoutTests/Stubs/StubRisk.swift, CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile
[PIMOB-2696](https://checkout.atlassian.net/browse/PIMOB-2696?atlOrigin=eyJpIjoiMjljNzBkOWI1M2Q0NGExMWI1ZmI1YTI4MGNlMTEzYmUiLCJwIjoiaiJ9)
Unblocks #542 
Risk team had a development that made Frames’s completion block to await their completion. This ended up with some merchants getting blocked by the response of Risk SDK. We had a long chat and decided the issue is because of another 3rd party dependency that the Risk SDK uses: FingerPrint SDK. Now we agreed with the Risk team to have a Frames development to timeout after a definitive timeframe to stop waiting for Risk SDK result and just call the callback with the token that’s already at hand.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> Implement timeout for Risk SDK

.github/CHANGELOG.md, Checkout.podspec, Checkout/Samples/CocoapodsSample/Podfile, Checkout/Source/Logging/CheckoutLogEvent.swift, Checkout/Source/Tokenisation/CheckoutAPIService.swift, Checkout/Source/Validation/Constants.swift, CheckoutTests/Stubs/StubRisk.swift, CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift, Frames.podspec, Source/Core/Constants/Constants.swift, iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj, iOS Example Frame/Podfile
[PIMOB-2696](https://checkout.atlassian.net/browse/PIMOB-2696?atlOrigin=eyJpIjoiYjgyMTRkMTM3NGNkNGY4N2E5MDgwYWE5ODEzNDJhMTEiLCJwIjoiaiJ9)
Update main branch with the changes from v4.3.7
[PIMOB-2696]: https://checkout.atlassian.net/browse/PIMOB-2696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Merge release/4.3.7 into main
