scripts/push.sh

Fix push script

---

Source/ErrorResponse.swift

- avoid inaccessible due to 'internal' protection level by adding public access

Error Response property access

---

CHANGELOG.md
Frames.podspec

* [x ] Bugfix (non-breaking change which fixes an issue)
* [ x] Lint and unit tests pass locally with my changes
Update change log and pod spec for minor release 3.0.5

MPI-243 : update pod spec version to 3.0.5 and change log

---

.travis.yml
CHANGELOG.md
Frames.podspec

Update Frames podspec version for the new 3.1.0 release.

Update Podspec and Changelog for 3.1.0 release

---

CHANGELOG.md
Frames.podspec

Update Podspec to 3.1.1

---

Source/CardViewController.swift
Source/CheckoutAPIClient.swift
Source/NetworkError.swift
iOS Example Custom/iOS Example Custom/ViewController.swift

Removed force unwrapping for new methods.

PIMOB-347: Removed force unwraps for new methods

---

Source/DetailsInputView.swift

Fixes https://github.com/checkout/frames-ios/issues/34.

Fix compilation issues in DetailsInputView in IB

---

FramesIos.xcodeproj/project.pbxproj
Source/CardViewController.swift
Tests/CardViewControllerTests.swift
Tests/StubCardViewControllerDelegate.swift
Tests/StubCheckoutAPIClient.swift

Return an error when the API client returns an error.

Return correct failure status to delete when error.

---

CHANGELOG.md
Frames.podspec

Release 3.2.0.

---

CHANGELOG.md
Frames.podspec

Release 3.3.0 updated changelog and Podspec

---

Documentation/Customizing the Card View.md
README.md
iOS Example Frame/iOS Example Frame/MainViewController.swift

Changes the example usage of `CardViewController` so it is only initialised once. Resolves #13.

Update example code to initialise CardViewController once.

---

Source/CheckoutAPIClient.swift
Tests/Core/CheckoutAPIClientTests.swift

- Use `checkout-sdk-frames-ios/\(framesVersion)` as `User-Agent` header
- None

PIMOB-572: use frames user agent

---

README.md
Source/UI/Delegates/CardViewControllerDelegate.swift

Updates README with correct documentation, usage, and headless mode.

Update README and add doc for delegate method.

---

CHANGELOG.md
Frames.podspec
README.md
Source/CheckoutAPIClient+Constants.swift

Update CHANGELOG for 3.4.0.

---

CHANGELOG.md
Frames.podspec
Source/CheckoutAPIClient+Constants.swift
iOS Example Frame/Podfile.lock
iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj

Getting ready to release version `3.4.1`

Update CHANGELOG and version for 3.4.1

---

Source/UI/Controllers/CardViewController.swift
Tests/UI/CardViewControllerTests.swift

- Call `paymentFormPresented` on every add to view hierarchy rather than once per instance on view load.

PIMOB-478: fix call logs at correct interval

---

Source/UI/Controllers/CardViewController.swift
Tests/UI/CardViewControllerTests.swift

- suppress log when navigating to AddressViewController

PIMOB-478: fix log after visiting address form

---

CHANGELOG.md
Frames.podspec
Source/CheckoutAPIClient+Constants.swift

Update CHANGELOG and version for 3.4.2

---

Source/CheckoutAPIClient.swift
Source/Core/CkoAddress.swift
Source/Core/CkoCardTokenRequest.swift
Source/UI/Controllers/CardViewController.swift
Tests/Core/CardUtilsTests.swift
Tests/Core/CheckoutAPIClientTests.swift
Tests/Fixtures/ckoCardTokenBillingDetails.json
iOS Example Frame/Podfile.lock
iOS Example Frame/iOS Example Frame/MainViewController.swift
iOS Example Frame/iOS Example FrameUITests/iOS_Example_FrameUITests.swift

* [x ] Bugfix (non-breaking change which fixes an issue)
* [ x] Lint and unit tests pass locally with my changes
* [ x] I have added tests that prove my fix is effective or that my feature works
If this is a relatively large or complex change, …

PI-1100 : using the right json encoder to fix billing address line 1 & 2 

---

iOS Example Custom/Podfile.lock
iOS Example Custom/iOS Example Custom/ViewController.swift

* [ x] Bugfix (non-breaking change which fixes an issue)

PI-1103 : Fix iOS Custom Example project Crashes while creating Token

---

CHANGELOG.md
Frames.podspec
Source/CheckoutAPIClient+Constants.swift

- Update version to 3.4.3
- Update `CHANGELOG.md`

Update CHANGELOG and version for 3.4.3

---

Source/CheckoutAPIClient.swift
Tests/Core/CheckoutAPIClientTests.swift

PI-1068: Update token type

---

.codebeatignore
.jazzy.yaml
.swiftlint.yml
codecov.yml

PI-1194: Remove PhoneNumberKit exclusions

---

Source/CheckoutAPIClient.swift
Source/Core/Logging/FramesLogEvent.swift
Source/Core/Logging/NetworkFlowLogger.swift
Source/Core/Logging/NetworkFlowLoggerFactory.swift
Tests/Core/Logging/FramesEventLoggerTests.swift
Tests/Core/Logging/FramesLogEventTests.swift
Tests/Core/Logging/NetworkFlowLoggerTests.swift

PI-1157: Implement public key logging

---

Source/Core/Logging/FramesLogEvent.swift
Source/Core/Logging/NetworkFlowLogger.swift
Tests/Core/Logging/FramesLogEventTests.swift
Tests/Core/Logging/NetworkFlowLoggerTests.swift

PI-1145: Implement token ID logging

---

Source/Core/URLHelper.swift
Source/Extensions/URL+Extensions.swift
Source/UI/Controllers/ThreedsWebViewController.swift
Source/UI/Delegates/ThreedsWebViewControllerDelegate.swift
Tests/Core/Extensions/URL+ExtensionsTests.swift
Tests/Core/URLHelperTests.swift
Tests/UI/ThreedsWebViewControllerTests.swift
iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
iOS Example Frame/iOS Example Frame/Base.lproj/Main.storyboard
iOS Example Frame/iOS Example Frame/MainViewController.swift

- Added new callbacks for 3DS completion to pass token back to merchants
- Removed force unwrapping optionals in `ThreedsWebViewController`
- Added tests for 3DS completion callbacks
Documentation will be updated as part of [feature/PI-1174-update-documentation](https://github.com/checkout/frames-ios/tree/feature/PI-1174-update-documentation)

PI-1285: Extract token from 3DS flow

---

Frames.podspec
bitrise.yml
iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj
iOS Example Frame/iOS Example Frame.xcodeproj/xcshareddata/xcschemes/iOS Example Frame.xcscheme
iOS Example Frame/iOS Example Frame.xcodeproj/xcuserdata/Harry.Brown.xcuserdatad/xcschemes/xcschememanagement.plist

- Set architectures in `Frames.podspec` to work with podspec from CheckoutEventLoggerKit
- Add iOS Example Frame scheme to repo
- Update `bitrise.yml`

PI-XXX: fix podspec for working with CheckoutEventLoggerKit

---

Source/Core/Logging/MetadataKey.swift

Correct `correlationId` to `CorrelationId` for logs

PI-1465: fix correlation ID field for logs

---

.swiftpm/xcode/xcshareddata/xcschemes/Frames.xcscheme
Package.swift
Source/Core/CheckoutAPIService.swift
Source/UI/Controllers/AddressViewController.swift
Source/UI/Controllers/CardViewController.swift
Source/UI/Views/CardNumberInputView.swift
Source/UI/Views/CardView.swift
Tests/Core/CardUtilsTests.swift
Tests/Mocks/AddressViewControllerMockDelegate.swift
Tests/Mocks/CardViewControllerMockDelegate.swift
Tests/Mocks/StubCardValidator.swift
Tests/Mocks/StubCardViewControllerDelegate.swift
Tests/Mocks/StubCheckoutAPIService.swift
Tests/UI/AddressViewControllerTests.swift
Tests/UI/CardNumberInputViewTests.swift
Tests/UI/CardViewControllerTests.swift
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

PI-1641: update tests to use Checkout and remove union pay

---

Source/CheckoutAPIClient.swift
Source/Core/Environment.swift
Source/Core/Logging/FramesLogEvent.swift
Tests/Core/CheckoutAPIClientTests.swift
Tests/UI/CardViewControllerTests.swift

- Log when `CheckoutAPIClient` is initialised
- Tests for the above

PI-1661: log CheckoutAPIClient init

---

Source/UI/Controllers/CardViewController.swift
Tests/UI/CardViewControllerTests.swift

* [ X] Bugfix (non-breaking change which fixes an issue)
* [X ] Lint and unit tests pass locally with my changes
* [ X] I have added tests that prove my fix is effective or that my feature works
If this is a relatively large or complex change, …

PI-1688 : fix payment form presented log entires

---

Source/CheckoutAPIClient.swift
Source/Core/Logging/FramesLogEvent.swift
Tests/Core/CheckoutAPIClientTests.swift

- Change `checkout_api_service_initialised` to `checkout_api_client_initialised`
- Update tests for the above

PI-1661: rename checkout api service log to checkout api client log

---

.swiftpm/xcode/xcshareddata/xcschemes/Frames.xcscheme
Source/Core/Constants.swift
Source/Core/Logging/FramesEventLogger.swift
Source/Core/Logging/FramesLogEvent.swift
Source/Core/Logging/PropertyProviding.swift
Source/Core/Logging/Theme.swift
Source/Extensions/ErrorResponse+PropertyProviding.swift
Source/Extensions/UIBarStyle+stringValue.swift
Source/Extensions/UIColor+PropertyProviding.swift
Source/Extensions/UIFont+PropertyProviding.swift
Source/UI/Controllers/CardViewController.swift
Tests/Core/Extensions/UIBarStyle+stringValueTests.swift
Tests/Core/Extensions/UIColor+PropertyProvidingTests.swift
Tests/Core/Extensions/UIFont+PropertyProvidingTests.swift
Tests/Core/Logging/FramesLogEventTests.swift
Tests/Core/Logging/ThemeTests.swift
Tests/Mocks/StubTheme.swift
Tests/Resources/ResourcesTests.swift
Tests/UI/CardViewControllerTests.swift
Tests/UI/DetailsInputViewTests.swift
iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj

- Add theme and device language to `paymentFormPresented` log
- Tests for the above
N/A

PI-1670: log theme and language for payment form

---

Source/Core/Logging/FramesLogEvent.swift
Source/UI/Controllers/ThreedsWebViewController.swift
Tests/UI/ThreedsWebViewControllerTests.swift

PI-1669: add log events for 3ds webview

---

bitrise.yml
iOS Example Frame/Podfile.lock

Update bitrise.yml so that we can version and maintain our ci config in git

PI-XXXX: update bitrise.yml

---

Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine1/DefaultBillingFormAddressLine1CellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/AddressLine2/DefaultBillingFormAddressLine2CellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/City/DefaultBillingFormCityCellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/Country/DefaultBillingFormCountryCellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/FullName/DefaultBillingFormFullNameCellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/PhoneNumber/DefaultBillingFormPhoneNumberCellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/Postcode/DefaultBillingFormPostCodeCellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/State/DefaultBillingFormStateCellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Main/DefaultBillingFormHeaderCellStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Title/DefaultHeaderLabelFormStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Main/DefaultBillingFormStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/Elements/Country/Country.swift
Source/UI/NewUI/BillingForm/Default Implementation/Elements/Error/DefaultErrorInputLabelStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/Elements/Hint/DefaultHintInputLabelStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift
Source/UI/NewUI/BillingForm/Default Implementation/Elements/Title/DefaultTitleLabelStyle.swift

- Please review this PR https://github.com/checkout/frames-ios/pull/160 firstly.
Update default billing form style implementation to to be public

Feature/PIMOB-1224: Update default billing form style implementation to to be public

---

Source/UI/NewUI/BillingForm/Default Implementation/Elements/TextField/DefaultTextField.swift
Source/UI/NewUI/CommonUI/Protocols/Elements/ElementTextFieldStyle.swift
Source/UI/NewUI/CommonUI/View/TextFieldView.swift
Tests/UI/New UI/BillingForm/View/BillingFormButtonViewTests.swift
Tests/UI/New UI/BillingForm/View/BillingFormTextFieldViewTests.swift

[Jira Ticket ](https://checkout.atlassian.net/browse/PIMOB-1240)
For textFields Change the border edges: 
cornerRadius and borderWidth properties should be injected and allowed by merchants to be customised.

Add textFields border style

---

Source/UI/NewUI/BillingForm/View/BillingFormPhoneNumberText.swift
Source/UI/NewUI/BillingForm/View/BillingFormTextField.swift
Source/UI/NewUI/BillingForm/View/MainBillingFormTextField.swift
Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift
Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
Source/UI/NewUI/CommonUI/View/TableViewCell/CellTextField.swift
Source/UI/NewUI/CommonUI/View/TextFieldView.swift
Tests/Mocks/BillingFormTextFieldCellMockDelegate.swift
Tests/Mocks/BillingFormViewControllerMockDelegate.swift
Tests/UI/New UI/BillingForm/View/BillingFormFullNameTextFieldCellTests.swift
Tests/UI/New UI/BillingForm/ViewModel/BillingFormViewModelTests.swift
iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj

Fix Phone number text field issue

PIMOB-XXXX: Fix Phone number text field issue

---

Source/UI/Controllers/CardViewController.swift
Source/UI/NewUI/BillingForm/ViewModel/BillingFormViewModel.swift
Source/UI/NewUI/CommonUI/View/TableViewCell/CellButton.swift

[Jira Ticket](https://checkout.atlassian.net/jira/software/c/projects/PIMOB/boards/988?modal=detail&selectedIssue=PIMOB-1240)
Remove old `TODO`

Remove old `TODO`

---

Source/UI/NewUI/BillingForm/ViewController/BillingFormViewController.swift
Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
Source/UI/NewUI/CommonUI/View/SelectionButtonView.swift
Source/UI/NewUI/CommonUI/View/TableViewCell/SelectionButtonTableViewCell.swift
Tests/UI/New UI/BillingForm/View/BillingFormButtonViewTests.swift
iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj

Clean `CellButton` code

---

Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
Tests/UI/New UI/BillingForm/ViewModel/BillingFormViewModelTests.swift

When `iso3166Alpha2` is not set by the merchant then use local device region 

Fix country region to be device local region

---

Source/Core/Constants+LocalizationKeys.swift
Source/Extensions/UIViewExtensions.swift
Source/Resources/en.lproj/Localizable.strings
Source/UI/Controllers/CardViewController.swift
Source/UI/NewUI/BillingForm/Factory/BillingFormFactory.swift
Source/UI/NewUI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
Source/UI/NewUI/CommonUI/View/Component/SelectionButtonView.swift
Source/UI/NewUI/CommonUI/View/Core/ButtonView.swift
Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentFormStyle.swift
Source/UI/NewUI/PaymentForm/Default Implementation/ExpiryDate/DefaultExpiryDateFormStyle.swift
Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentFormStyle.swift
Source/UI/NewUI/PaymentForm/View/BillingSummary/BillingFormSummaryView.swift
Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
Source/UI/NewUI/PaymentForm/ViewModel/PaymentViewModel.swift
Source/UI/Views/CardView.swift
Tests/UI/CardViewControllerTests.swift
Tests/UI/New UI/BillingForm/View/BillingFormSummaryViewTests.swift
Tests/UI/New UI/BillingForm/ViewModel/BillingFormViewModelTests.swift
iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
iOS Example Frame Carthage/iOS Example FrameUITests/iOS_Example_FrameUITests.swift
iOS Example Frame/iOS Example Frame/CustomStyle1.swift
iOS Example Frame/iOS Example Frame/CustomStyle2.swift
iOS Example Frame/iOS Example Frame/MainViewController.swift
iOS Example Frame/iOS Example FrameUITests/iOS_Example_FrameUITests.swift

Please review this firstly https://github.com/checkout/frames-ios/pull/183
[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1191?atlOrigin=eyJpIjoiYzExZjk1NDIzMjdjNDQ4MWFhNWMxZDVkOTc2NGM4NzAiLCJwIjoiaiJ9)
Add Expiry Date UI only

Add Expiry Date UI without logic

---

Source/UI/NewUI/CommonUI/View/TableViewCell/SelectionButtonTableViewCell.swift
Source/UI/NewUI/PaymentForm/View/BillingSummary/BillingFormSummaryView.swift
Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
iOS Example Frame/iOS Example Frame/MainViewController.swift

BugFix: Fixed issues from show and tell meeting

---

Source/Core/Constants+LocalizationKeys.swift
Source/Core/Constants+Style.swift
Source/Resources/en.lproj/Localizable.strings
Source/UI/NewUI/BillingForm/View/BillingFormCellTextField.swift
Source/UI/NewUI/CommonUI/View/Component/InputView.swift
Source/UI/NewUI/CommonUI/View/Core/TextFieldView.swift
Source/UI/NewUI/PaymentForm/Default Implementation/ExpiryDate/DefaultExpiryDateFormStyle.swift
Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1274?atlOrigin=eyJpIjoiMDM3ODgxNTJlYTU3NDJlNWJlMGViNzlkNTRmYjY3NjMiLCJwIjoiaiJ9)
please review this PR firstly https://github.com/checkout/frames-ios/pull/191
If this is a relatively large …

Feature/PIMOB-1274: Expiry date error messages

---

Source/Resources/en.lproj/Localizable.strings

jira 
[ticket 1 ](https://checkout.atlassian.net/jira/software/c/projects/PIMOB/boards/988?modal=detail&selectedIssue=PIMOB-1304)
[ticket 2](https://checkout.atlassian.net/jira/software/c/projects/PIMOB/boards/988?modal=detail&selectedIssue=PIMOB-1191) 
- Lower case validation text for security code / expiry date / card number
- 'Please enter a valid security code'
- 'Please enter a valid expiry date'
- 'Please enter a valid card number'
- ExpiryDate label should be ‘Expiry date’ - needs a space and a lower case d 
- The figma design shows a additional space after -- and also addition space after /
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder …

PIMOB-1911: Fix localisation

---

Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
Source/UI/NewUI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
Source/UI/NewUI/PaymentForm/ViewModel/PaymentViewModel.swift
Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
Tests/UI/New UI/BillingForm/ViewModel/PaymentViewModelTests.swift
Tests/UI/New UI/PaymentFormFactoryTests.swift
iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
iOS Example Frame/iOS Example Frame/MainViewController.swift

[Jira ticket](https://checkout.atlassian.net/jira/software/c/projects/PIMOB/boards/988?modal=detail&selectedIssue=PIMOB-1191)
ExpiryDateView(environment: viewModel.environment) is public and needs to pass in the environment for merchants to add this to their UI. 
Instead the ExpiryDateView should take in a CardValidator in the init method.  …

Add CardValidator to payment view model

---

Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
Source/UI/NewUI/BillingForm/Default Implementation/Elements/Country/Country.swift
Source/UI/NewUI/CommonUI/Protocols/Elements/ElementButtonStyle.swift
Source/UI/NewUI/CommonUI/View/Component/SelectionButtonView.swift
Source/UI/NewUI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultAddBillingDetailsButtonStyle.swift
Source/UI/NewUI/PaymentForm/Default Implementation/BillingFormSummary/Summary/Button/DefaultEditBillingDetailsButtonStyle.swift
Source/UI/NewUI/PaymentForm/Factory/PaymentFormFactory.swift
Source/UI/NewUI/PaymentForm/View/BillingFormSummaryView.swift
Tests/UI/New UI/PaymentFormFactoryTests.swift
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/xcshareddata/xcschemes/iOS Example Frame.xcscheme
iOS Example Frame/iOS Example Frame/CustomStyle1.swift
iOS Example Frame/iOS Example Frame/CustomStyle2.swift
iOS Example Frame/iOS Example Frame/MainViewController.swift

`shouldImageFlippedForRightToLeftLayoutDirection` is provided by the merchant

`shouldImageFlippedForRightToLeftLayoutDirection` is provided by the merchant

---

Source/UI/NewUI/PaymentForm/View/SecurityCodeView.swift
Tests/UI/New UI/BillingForm/View/SecurityCodeViewTests.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1191?atlOrigin=eyJpIjoiNThlZTQ4ZTg5M2I5NGUzN2FlYmJmYWRlNTc5YzgxMTIiLCJwIjoiaiJ9
)
Fix: Invalid string case of of pre-filled security code text.

Fix: Invalid string case of of pre-filled security code text.

---

Source/UI/NewUI/BillingForm/Default Implementation/BillingForm/Fields/State/DefaultBillingFormStateCellStyle.swift

County should not be a mandatory field by default

PIMOB-1337: County billing form field should be optional

---

Source/UI/NewUI/PaymentForm/View/ExpiryDateView.swift
Tests/UI/New UI/BillingForm/View/ExpiryDateViewTests.swift
iOS Example Frame/iOS Example Frame/CustomStyle1.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1191?atlOrigin=eyJpIjoiNThlZTQ4ZTg5M2I5NGUzN2FlYmJmYWRlNTc5YzgxMTIiLCJwIjoiaiJ9
)
Fix: Invalid string case of of pre-filled expiry date text.

PIMOB-1191: Invalid string case of of pre-filled expiry date text.

---

Source/Core/Constants/Constants+Padding.swift
Source/Extensions/UIViewControllerExtensions.swift
Source/UI/Controllers/CardViewController.swift
Source/UI/Controllers/CountrySelectionViewController.swift
Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentFormStyle.swift
Source/UI/NewUI/PaymentForm/Default Implementation/DefaultPaymentHeaderCellStyle.swift
Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentFormStyle.swift
Source/UI/NewUI/PaymentForm/StyleProtocol/PaymentHeaderCellStyle.swift
Source/UI/NewUI/PaymentForm/View/PaymentHeaderView.swift
Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift
Source/UI/NewUI/PaymentForm/ViewModel/PaymentViewModel.swift
iOS Example Frame/iOS Example Frame/CustomStyle1.swift
iOS Example Frame/iOS Example Frame/CustomStyle2.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1266?atlOrigin=eyJpIjoiZGZhZTU3NjZmNWRmNDJkY2FkMzc3ZDBkNDJhYzYyMjkiLCJwIjoiaiJ9)
- Update header view background color
- Show title on navigation bar on scroll 
- Update Payment screen background color
- Add all card scheme icons into Custom 1 
- Remove subtitle from Custom1
- Remove all card scheme  from Custom2
https://user-images.githubusercontent.com/102961713/182137920-1d1c9cd4-b26b-4e2a-ad18-c396f833fba9.mov
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …

PIMOB-1266: Update header view on scroll

---

README.md

Update the link for the customization documentation.

README link update 

---

README.md

PIMOB-XXXX: Update README

---

Source/Extensions/UIViewControllerExtensions.swift
Source/UI/Controllers/CardViewController.swift
Source/UI/Controllers/CountrySelectionViewController.swift
Source/UI/NewUI/PaymentForm/View/PaymentHeaderView.swift
Source/UI/NewUI/PaymentForm/ViewController/PaymentViewController.swift

[Jira task](https://checkout.atlassian.net/browse/PIMOB-1374)
- Make navigation controller title standard to OS
- Fix header background to behave as intended in landscape mode

PIMOB-1374: Minor UI changes

---

Source/Core/Models/CardScheme.swift
Tests/Core/CardSchemeTests.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1365?atlOrigin=eyJpIjoiZDA5ZDNhODk4NGNhNDYxOGI5MGIxMTI1MTVjYTkwNGUiLCJwIjoiaiJ9) …

PIMOB-1365: Not allow any merchant to pass `unknown` card scheme

---

Source/UI/CommonUI/View/Component/SelectionButtonView.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1395?atlOrigin=eyJpIjoiNDE0NmRiYjBiZGJmNGQ0YTk2MzFjMDY3NWFhYmJkYWUiLCJwIjoiaiJ9) …

PIMOB-1395: Fix add billing form when click on the chevron 

---

Source/UI/CommonUI/View/Component/InputView.swift

[Jira ticket ](https://checkout.atlassian.net/browse/PIMOB-1370?atlOrigin=eyJpIjoiOTVjNDc1YzU5OGFkNGJhZmEwMzkzNjRjY2ZiZmRlMWIiLCJwIjoiaiJ9) …

PIMOB-1370: Fix Input UI components spaces

---

Source/UI/PaymentForm/View/BillingFormSummaryView.swift

Fix summary button click
[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1395?atlOrigin=eyJpIjoiYTlhN2ZiMmJkZGE3NGRjNmI5NGJmZmE1YmY5YjE0MzgiLCJwIjoiaiJ9)
If this is a relatively large or complex change, kick off the discussion by …

PIMOB-1395: Fix summary button click

---

Source/UI/CommonUI/View/Core/SecureDisplayView.swift
Source/UI/CommonUI/View/Core/TextFieldView.swift
Tests/UI/BillingForm/View/SecureDisplayViewTests.swift
bitrise.yml

[Jira task](https://checkout.atlassian.net/browse/PIMOB-1376)
Update SecureDisplayView to reflect source repository and integrate with it to fix keyboard responder behaviour.

PIMOB-1376: Fix input behaviour

---

Source/Resources/en.lproj/Localizable.strings
iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift

[Jira task](https://checkout.atlassian.net/browse/PIMOB-1417)
Update default text content as required for CustomStyle1. Setup generic default text for Default implementation as we cannot sync a localisable string with what consumer can actually accept.
| Default Localisable     | Custom Style Provided |
| ---      | ---       |
| ![Screenshot 2022-08-31 at 11 42 29](https://user-images.githubusercontent.com/102028170/187660856-50e0af9d-7b14-4322-9dd3-cfc0e2f8f306.png) | ![Screenshot 2022-08-31 at 11 42 21](https://user-images.githubusercontent.com/102028170/187660862-4b862ce3-4cc2-41cd-8082-3178024e5ea4.png) |

PIMOB-1417: Update text content

---

Source/UI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1396?atlOrigin=eyJpIjoiMmE1NDZkZGE3YzA0NDYzNDhlZWE5ZjBhMjQwMWYzOTkiLCJwIjoiaiJ9) …

PIMOB-1396: Fix Done states validation in the Billing Form 

---

Source/UI/PaymentForm/ViewController/PaymentViewController.swift
iOS Example Frame/iOS Example Frame/Factory/Factory.swift
iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift

[Jira ticket ](https://checkout.atlassian.net/browse/PIMOB-1375)

PIMOB-1375: Fix iPad scroll view background

---

Source/UI/BillingForm/View/BillingFormHeaderCell.swift
Source/UI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift
Source/UI/PaymentForm/View/BillingFormSummaryView.swift
Source/UI/Theme/Generic/Theme+Button.swift
bitrise.yml
iOS Example Frame/iOS Example Frame/Factory/Factory+UITest.swift
iOS Example Frame/iOS Example Frame/Factory/Factory.swift
iOS Example Frame/iOS Example FrameUITests/FrameUITests.swift
iOS Example Frame/iOS Example FrameUITests/XCUIApplication+Extension.swift

[Jira task](https://checkout.atlassian.net/browse/PIMOB-1416)
Ended up covering a few minor fixes that came out from the UI test.

PIMOB-1416: Add UI Test for full UI journey

---

iOS Example Frame/iOS Example Frame/Style/CustomStyle1.swift

[Jira task](https://checkout.atlassian.net/browse/PIMOB-1058)

PIMOB-1058: Change summary billing button size

---

Source/UI/BillingForm/View/BillingFormPhoneNumberText.swift

[Jira issue](https://checkout.atlassian.net/browse/PIMOB-1058?focusedCommentId=186713)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

PIMOB-1058: Fix strong reference to phoneNumberTextDelegate

---

Source/UI/CountrySelection/CountrySelectionViewController.swift
iOS Example Frame/iOS Example Frame/AppDelegate.swift

[Jira issues](https://checkout.atlassian.net/browse/PIMOB-1058?focusedCommentId=186713)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

PIMOB-1058: Disable dark mode for Frames and Sample app

---

Source/UI/CommonUI/View/Component/InputView.swift
iOS Example Frame/iOS Example FrameUITests/FrameUITests.swift

[Jira issue](https://checkout.atlassian.net/browse/PIMOB-1058?focusedCommentId=186713)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

PIMob-1058: Missing border line colors for UIStackView on iOS 12

---

Checkout/CarthageSample/CheckoutCarthageSample.xcodeproj/project.pbxproj

PIMOB-XXXX: Change Checkout Carthage min iOS version to 12

---

Checkout/CocoapodsSample/CheckoutCocoapodsSample.xcodeproj/project.pbxproj
Checkout/CocoapodsSample/Podfile
Checkout/CocoapodsSample/Podfile.lock

PIMOB-XXXX: Change Checkout POD min iOS version to 12

---

Checkout/Package.swift
Checkout/SPMSample/CheckoutSPMSample.xcodeproj/project.pbxproj

Please review firstly this PR https://github.com/checkout/frames-ios/pull/290

PIMOB-XXXX: Change Checkout SPM min iOS version to 12

---

Source/Extensions/UIViewControllerExtensions.swift

[Jira issues ](https://checkout.atlassian.net/browse/PIMOB-1058?focusedCommentId=186713)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

PIMOB-1058: Fix Navigation bar is always shown on iOS 12

---

Source/UI/BillingForm/Default Implementation/BillingForm/Fields/Country/DefaultBillingFormCountryCellStyle.swift
Source/UI/BillingForm/Default Implementation/BillingForm/Header/Cancel/DefaultCancelButtonFormStyle.swift
Source/UI/BillingForm/Default Implementation/BillingForm/Header/Done/DefaultDoneFormButtonStyle.swift
Source/UI/BillingForm/ViewController/BillingFormViewController.swift

[Figma](https://www.figma.com/file/ABFqgxna0VH5TcfMgwnQHs/02-%E2%80%A2-Vision?node-id=2385%3A17689) 
[Jira](https://checkout.atlassian.net/browse/PIMOB-1441?atlOrigin=eyJpIjoiODE1YjRjY2Q4YzUwNDM3ZWFhYjAwYzI4YTZkMTBhZDciLCJwIjoiaiJ9)
**Issues**
**Fix**
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

PIMOB-1441: Address default theme UI comments for billing form screen

---

iOS Example Frame/iOS Example Frame/Storyboards/Base.lproj/Main.storyboard

[Figma](https://www.figma.com/file/ABFqgxna0VH5TcfMgwnQHs/02-%E2%80%A2-Vision?node-id=2385%3A17689) 
[Jira](https://checkout.atlassian.net/browse/PIMOB-1441?atlOrigin=eyJpIjoiODE1YjRjY2Q4YzUwNDM3ZWFhYjAwYzI4YTZkMTBhZDciLCJwIjoiaiJ9)
**Issues**
**Fix**

PIMOB-1441: Address default theme UI comments for Sample app home screen

---

Source/UI/BillingForm/ViewController/BillingFormViewController.swift

Change default styling of Billing Done Button.
| **Proposed** | **Now** |
|:---:|:---:|
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-22 at 13 11 27](https://user-images.githubusercontent.com/102028170/191751647-318844c4-c077-4c3c-9aa8-a637de0220be.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-22 at 13 12 26](https://user-images.githubusercontent.com/102028170/191751746-3ecdf0a6-236a-4b99-968f-6266cc97935a.png) |

PIMOB-1441: Billing Nav Controller Buttons Font

---

Source/Resources/nl.lproj/Localizable.strings

| Payment Form | Billing Form | Country Selection |
|:-:|:-:|:-:|
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-22 at 17 52 11](https://user-images.githubusercontent.com/102028170/191807035-9f25038f-f56a-421b-a8e1-b5c33ed95fcb.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-22 at 17 52 18](https://user-images.githubusercontent.com/102028170/191807231-95890860-0971-4775-8fff-d323962e0c36.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-22 at 17 52 26](https://user-images.githubusercontent.com/102028170/191806828-547651e7-dacd-4e26-b657-1df94b9be013.png) |
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-09-22 at 17 52 13](https://user-images.githubusercontent.com/102028170/191806940-6fd19bf3-6e01-4b0a-afbb-98c20c346559.png) | ![Simulator Screen Shot - iPhone 14 Pro - …

PIMOB-1234: Add Dutch localisation

---

Source/UI/BillingForm/ViewController/BillingFormViewController.swift
Source/UI/BillingForm/ViewModel/DefaultBillingFormViewModel.swift

Dynamically update default state of the Billing Form Done button.

PIMOB-XXXX: Billing Form Done button fix

---

Source/Extensions/UINavigationControllerExtensions.swift
Source/Extensions/UIViewControllerExtensions.swift
Source/UI/BillingForm/FramesFactory.swift
Source/UI/BillingForm/ViewController/BillingFormViewController.swift
Source/UI/CountrySelection/CountrySelectionViewController.swift
Source/UI/PaymentForm/ViewController/PaymentViewController.swift
Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
Tests/Core/Extensions/UINavigationControllerTests.swift
iOS Example Frame Carthage/iOS Example Frame Carthage.xcodeproj/project.pbxproj
iOS Example Frame/iOS Example Frame/Extension/UIViewControllerExtension.swift
iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift

[Jira ticket](https://checkout.atlassian.net/browse/PIMOB-1474)
**Screenshot:**

PIMOB-1474: Move navigation bar theme logic from Frames SDK to the host app

---

Source/Extensions/UINavigationControllerExtensions.swift
Tests/Core/Extensions/UINavigationControllerTests.swift
iOS Example Frame/iOS Example Frame/Extension/UIViewControllerExtension.swift
iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift

Support coping old navigation bar style

PIMOB-1474: Support old navigation bar integration for background color

---

iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift

PIMOB-1474: Revert default UI navigation bar color to white

---

Frames.podspec

PIMOB-XXX: Fix missing pod project assets on main

---

CHANGELOG.md
Checkout/Checkout/Source/Validation/Constants.swift
CheckoutTests/Network/RequestFactoryTests.swift
Frames.podspec
Source/Core/Constants/Constants.swift

Changes for 4.0.3 release were done in a branch and not included in `main`.

Update main with latest release changes

---

README.md
iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift

Updating ReadMe to convey the appearance of a new failure type and its separate handling, as well as improving the sample application to apply these changes

Release 4.0.4: Update ReadMe & sample app

---

Source/UI/PaymentForm/ViewModel/CardCreationModel.swift
Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
Tests/UI/BillingForm/ViewModel/CardCreationModelTests.swift
Tests/UI/BillingForm/ViewModel/PaymentViewModelTests.swift

[Jira task](https://checkout.atlassian.net/browse/PIMOB-1906)

PIMOB-1906: Enable optional CVV

---

Package.swift

Enforce SPM requirements to consume valid dependencies for the functionality

PIMOB-XXXX: Update Package.swift dependencies

---

bitrise.yml

Bitrise is being sourced from main branch's yml file so we need to merge this in to test our integration tests while they are being merged into develop.

Add integration checks bitrise workflow

---

Checkout/Source/Extension/Foundation+Extensions.swift
Checkout/Source/Protocols/CalendarProtocol.swift
Checkout/Source/Validation/Validators/CardValidator.swift
CheckoutTests/Stubs/StubCalendar.swift
CheckoutTests/Validation/CardValidatorTests.swift
README.md
Source/UI/PaymentForm/View/ExpiryDate/ExpiryDateFormatter.swift
Source/UI/PaymentForm/View/ExpiryDate/ExpiryDateView.swift
Source/UI/PaymentForm/ViewController/PaymentViewController.swift
Source/UI/PaymentForm/ViewModel/DefaultPaymentViewModel.swift
Tests/Mocks/MockExpiryDateViewDelegate.swift
Tests/Mocks/PaymentViewControllerMockDelegate.swift
Tests/UI/BillingForm/View/ExpiryDateFormatterTests.swift
Tests/UI/BillingForm/View/ExpiryDateViewTests.swift

Update `develop` branch with the latest changes from `main`

Main into develop

---

iOS Example Frame SPM/iOS Example Frame Regression Tests/ExpiryDateEdgeCaseTests.swift
iOS Example Frame SPM/iOS Example Frame Regression Tests/Helpers/StaticTexts.swift
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj

Covering expiry date edge cases.

Add expiry date edge case tests

---

iOS Example Frame SPM/iOS Example Frame Regression Tests/Helpers/XCUIApplication+TestHelpers.swift

Wait for keyboard to be collapsed down before taking the snapshot.

Fix Arabic keyboard button tap issue

---

Checkout/Source/Validation/Constants.swift
CheckoutTests/Network/RequestFactoryTests.swift
Frames.podspec

Fixing merge conflicts on a separate branch.

Fix develop into main merge conflicts

---

Checkout.podspec

Move Checkout.podspec

---

Checkout/Samples/CocoapodsSample/CheckoutCocoapodsSample.xcodeproj/project.pbxproj
Checkout/Samples/CocoapodsSample/Podfile
Checkout/Samples/CocoapodsSample/Podfile.lock
README.md
bitrise.yml
iOS Example Frame/Podfile
iOS Example Frame/Podfile.lock
iOS Example Frame/iOS Example Frame.xcodeproj/project.pbxproj

- Update sample project versions
- Update README recommendation
- Force CI to update pods till the next major version

Update samples and configurations

---

CheckoutTests/Integration/CheckoutAPIServiceIntegrationTests.swift

Fix Checkout tests

---

.github/CODEOWNERS.md

Add codeowners file

---

.github/workflows/check-pr.yml
.swiftlint.yml
Checkout/Source/Extension/StringExtensions.swift
Checkout/Source/Model/Card+Scheme.swift
Checkout/Source/Model/Country.swift
Checkout/Source/Model/ExpiryDate.swift
Checkout/Source/Network/NetworkManager.swift
Checkout/Source/Validation/Validators/CVVValidator.swift
Checkout/Source/Validation/Validators/CardNumberValidator.swift
Checkout/Source/Validation/Validators/CardValidator.swift
Checkout/Source/Validation/Validators/PhoneValidator.swift

Fix the fixable SwiftLint issues

---

.github/scripts/lintEditedFiles.sh
.github/workflows/check-pr.yml

Take the linter job into an `.sh` file to get a tidier look

Add lint edited files script

---

iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
iOS Example Frame/iOS Example Frame/Storyboards/Base.lproj/Main.storyboard
iOS Example Frame/iOS Example Frame/ViewController/HomeViewController.swift

Update security code component sample app

---

.gitignore
Checkout/Samples/SPMSample/CheckoutSPMSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
iOS Example Frame SPM/iOS Example Frame Regression Tests/ExpiryDateEdgeCaseTests.swift
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Apple recommends having the `Package.resolved` file under version control to have a reliable CI workflow. [Reference](https://developer.apple.com/documentation/xcode/building-swift-packages-or-apps-that-use-them-in-continuous-integration-workflows)

Include Package.resolved into git as per Apple recommendation

---

Checkout.podspec
Checkout/Source/Tokenisation/CheckoutAPIService.swift
CheckoutTests/Stubs/StubRisk.swift
CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift
Package.resolved
Package.swift
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iOS Example Frame/Podfile

PRISM-10522 - Add Risk package

---

.github/CHANGELOG.md
Checkout.podspec
Checkout/Samples/CocoapodsSample/Podfile
Checkout/Samples/SPMSample/CheckoutSPMSample.xcodeproj/project.pbxproj
Checkout/Samples/SPMSample/CheckoutSPMSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Checkout/Source/Tokenisation/CheckoutAPIService.swift
Checkout/Source/Validation/Constants.swift
CheckoutTests/Stubs/StubRisk.swift
CheckoutTests/Tokenisation/CheckoutAPIServiceTests.swift
Frames.podspec
Package.resolved
Package.swift
Source/Core/Constants/Constants.swift
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iOS Example Frame/Podfile

No public changes. Just the internal integration of the Risk SDK for opted-in merchants.

Release 4.3.2

---

Checkout/Source/Validation/Constants.swift
Source/Core/Constants/Constants.swift

Update logger versions

---

.github/CHANGELOG.md
Checkout.podspec
Checkout/Samples/CocoapodsSample/Podfile
Checkout/Source/Validation/Constants.swift
Frames.podspec
Source/Core/Constants/Constants.swift
iOS Example Frame SPM/iOS Example Frame SPM.xcodeproj/project.pbxproj
iOS Example Frame/Podfile

[PIMOB-2696](https://checkout.atlassian.net/browse/PIMOB-2696?atlOrigin=eyJpIjoiNmU1OTU4YTU2ZTQyNDE2NmIzMTM4N2JiN2Y0MDQ4YTkiLCJwIjoiaiJ9)
Updates release versions to 4.3.7 and updates sample project's dependency versions to same.
[PIMOB-2696]: https://checkout.atlassian.net/browse/PIMOB-2696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update samples and versions
